spring.application.name=backend


#Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/petrolbunk
spring.datasource.username=root
spring.datasource.password=123456

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver springboot autodetects type of driver because mysql driver dependency added in pom.xml


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT Configuration
jwt.secret=VGhpc0lzTXlWZXJ5U2VjcmV0S2V5Rm9yUGV0cm9sQnVua01hbmFnZW1lbnRTeXN0ZW0yMDI2
jwt.expiration=86400000

